#!/usr/bin/env python3
# orior - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
# Catalog: PRF-x-014
#
# The twiddle group of a number theoretic transform, the n-th roots of unity modulo a Proth prime, lit
# against the rest of the residue field and rendered through the engine's own renderer. The point the
# figure carries: the roots are a cyclic group under multiplication, an exact algebraic object, but their
# residues are spread across the field with no geometric arrangement. The order of the group is not
# visible to the eye and has to be tested. This is the geometric face of the half-order floor the twiddle certificate
# proves (EXP-x-007, examples/0_experimental/ntt_twiddle_certificate.py): a root of half the required
# order passes every cheap invariant, and only the order test catches it.
#
#   Usage:  python evidence/proofs/posits/proof_twiddle_group_in_field.py
#           The rendered figure is written to build/figures/twiddle_group_in_field.png, regenerated on
#           every run and not tracked. The generator is the tracked artifact; the image reproduces from it.
#
# The renderer is the reference host arm in archive/src/python/engine/render/host.py. Every value is an integer
# read off the corpus, placed by a bijective integer layout. No float, no trigonometry, no angle. This
# does not and cannot draw the roots on a geometric circle. That circle lives in the complex plane, at
# exp(2*pi*i*j/n), and reaching it needs floating point the engine refuses. The residues are what the
# transform actually computes with, and where they land is what this renders.
#
# Positive control: omega has multiplicative order exactly n, verified by the order test, and its n powers
# are distinct. Two routes to the same set: the group generated by omega equals the solution set of
# x^n == 1 (mod p), computed independently over the whole field. They agree, and those two routes are
# what the standing discipline asks for.
#
# Drawn null, three faults named:
#   subgroup      the half-order root omega^2 has order n/2 and generates a proper subgroup of n/2
#                 residues, a wrong root giving a smaller group.
#   cheap-blind   over the length-n twiddle table, the half-order root matches the correct one on the
#                 identity (w0 == 1), on the sum, on the sum of squares and on sampled group-law
#                 identities. Only the order test separates them, reproducing the certificate's own
#                 floor.
#   non-root      a value with x^n != 1 (mod p) is refused membership. The test can reject, and a test
#                 that cannot reject proves nothing.
#
# Floor: the figure renders one prime and one transform length. It verifies the honesty of this case, that
# the residues spread across the field and the order is invisible to the eye, and it does not prove
# equidistribution of a primitive root's powers in general. The render's own two arms, host and device,
# are graded byte-identical elsewhere (archive/utils/test/src/python/engine/render/render_test.py, utils/bench/bench_raster.c),
# and this posit uses the reference host arm so it runs from a fresh clone with no build.
#
# Prior art, named with respect: the roots of unity and their cyclic group are classical; the near-uniform
# spread of a primitive root's powers across the residues is a standard equidistribution result. Cited from
# memory of the literature, unread here. This file adds no new mathematics; it renders an exact set and
# checks the claims the figure's caption will make.

import os
import sys
import struct
import zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "src", "python"))
import manifest  # noqa: E402,F401
from render.host import raster, RasterConfig, LAYOUT_ROWS, CHANNEL_BYTE, REDUCE_MAX  # noqa: E402

PRIME = 12289          # 3 * 2^12 + 1, a Proth prime. P - 1 = 2^12 * 3
ORDER = 256            # the transform length; omega has multiplicative order exactly this

CLOUD = 45             # a residue that is not a root of unity: the ambient field
RING = 255             # a residue that is a root of unity: the twiddle group, lit
AMBIENT = 20           # a cell past p - 1: the field padded to fill the sheet, not a residue


def distinct_prime_factors(number):
    """The distinct primes dividing `number`, by trial division. Exact and unbounded."""
    factors = set()
    remaining = number
    divisor = 2
    while divisor * divisor <= remaining:
        while remaining % divisor == 0:
            factors.add(divisor)
            remaining //= divisor
        divisor += 1 if divisor == 2 else 2
    if remaining > 1:
        factors.add(remaining)
    return factors


def is_primitive_root(generator, prime, pminus1_factors):
    """Whether `generator` has order exactly prime - 1, the definition of a primitive root."""
    base = prime - 1
    return all(pow(generator, base // factor, prime) != 1 for factor in pminus1_factors)


def find_primitive_root(prime):
    """The smallest primitive root modulo `prime`, by the definition."""
    factors = distinct_prime_factors(prime - 1)
    for candidate in range(2, prime):
        if is_primitive_root(candidate, prime, factors):
            return candidate
    raise RuntimeError("no primitive root found")


def order_of(element, prime, bound):
    """The multiplicative order of `element`, given it divides `bound`. The walk is short by design."""
    for candidate in range(1, bound + 1):
        if bound % candidate == 0 and pow(element, candidate, prime) == 1:
            return candidate
    return None


def table_invariants(root, prime, length):
    """The cheap invariants of a length-n twiddle table, the ones a reader computes in O(n).

    Returns (identity, sum_mod, sum_squares_mod, group_law) matching the certificate's floor section.
    """
    table = [pow(root, exponent, prime) for exponent in range(length)]
    identity = table[0] == 1
    sum_mod = sum(table) % prime
    sum_squares_mod = sum((value * value) % prime for value in table) % prime
    group_law = all((table[left] * table[right]) % prime == table[(left + right) % length]
                    for left, right in ((1, 1), (3, 100), (200, 55), (255, 2), (128, 128)))
    return identity, sum_mod, sum_squares_mod, group_law


def write_png_gray(path, width, height, pixels):
    """A grayscale PNG, standard library only. `pixels` is width*height bytes, row major."""
    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    raw = bytearray()
    for row in range(height):
        raw.append(0)  # filter type 0, none
        start = row * width
        raw.extend(pixels[start:start + width])
    with open(path, "wb") as handle:
        handle.write(b"\x89PNG\r\n\x1a\n")
        handle.write(chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0)))
        handle.write(chunk(b"IDAT", zlib.compress(bytes(raw), 9)))
        handle.write(chunk(b"IEND", b""))


def scale_up(pixels, width, height, factor):
    """Nearest-neighbor integer scale. The lit points stay legible without a resampling filter."""
    big_width, big_height = width * factor, height * factor
    big = bytearray(big_width * big_height)
    for row in range(big_height):
        source_row = (row // factor) * width
        target_row = row * big_width
        for column in range(big_width):
            big[target_row + column] = pixels[source_row + (column // factor)]
    return big, big_width, big_height


def main():
    generator = find_primitive_root(PRIME)
    omega = pow(generator, (PRIME - 1) // ORDER, PRIME)

    # Positive control: order exactly n, and n distinct powers.
    assert order_of(omega, PRIME, ORDER) == ORDER, "omega must have order exactly ORDER"
    ring = [pow(omega, exponent, PRIME) for exponent in range(ORDER)]
    ring_set = set(ring)
    assert len(ring_set) == ORDER, "the roots of unity must be distinct"

    # Two routes to the same set: the group generated by omega, and the solutions of x^n == 1.
    solution_set = {value for value in range(1, PRIME) if pow(value, ORDER, PRIME) == 1}
    assert solution_set == ring_set, "the generated group must equal the solution set of x^n == 1"

    # Drawn null, fault one: the half-order root gives a proper subgroup of half the residues.
    impostor = pow(omega, 2, PRIME)
    assert order_of(impostor, PRIME, ORDER) == ORDER // 2, "the impostor must have order n/2"
    impostor_set = {pow(impostor, exponent, PRIME) for exponent in range(ORDER // 2)}
    assert len(impostor_set) == ORDER // 2, "the impostor group must be half the size"
    assert impostor_set < ring_set, "the impostor group must be a proper subgroup of the correct one"

    # Drawn null, fault two: the cheap invariants match, only the order test separates them.
    right = table_invariants(omega, PRIME, ORDER)
    wrong = table_invariants(impostor, PRIME, ORDER)
    assert right == wrong, "the half-order table must match the correct one on every cheap invariant"
    assert right[0] is True and right[1] == 0 and right[2] == 0 and right[3] is True, \
        "the correct table must pass identity, sum zero, sum-of-squares zero and the group law"

    # Drawn null, fault three: a non-root is refused.
    non_root = next(value for value in range(2, PRIME) if pow(value, ORDER, PRIME) != 1)
    assert non_root not in ring_set, "a value with x^n != 1 must not be a member"

    # Render the correct group in the field, through the reference host arm.
    width = height = 111                 # 111 * 111 = 12321 >= PRIME, the field fills the sheet
    cells = width * height
    corpus = bytearray(cells)
    for position in range(cells):
        if position >= PRIME:
            corpus[position] = AMBIENT
        elif position in ring_set:
            corpus[position] = RING
        else:
            corpus[position] = CLOUD

    config = RasterConfig(width=width, height=height, layout=LAYOUT_ROWS,
                          channel=CHANNEL_BYTE, reduce=REDUCE_MAX, gain=1)
    needle = bytes(corpus[0:1])          # length one. Alignments == cells and every cell fills once
    sheet = raster(config, corpus, needle, [])
    assert sheet is not None and len(sheet) == cells, "the render was refused or returned the wrong size"
    lit = sum(1 for value in sheet if value == RING)
    assert lit == ORDER, "the lit cells must be exactly the n roots of unity"

    figures = os.path.join(ROOT, "build", "figures")
    os.makedirs(figures, exist_ok=True)
    out = os.path.join(figures, "twiddle_group_in_field.png")
    big, big_width, big_height = scale_up(sheet, width, height, 5)
    write_png_gray(out, big_width, big_height, big)

    print("prime %d, primitive root %d, omega %d, order %d" % (PRIME, generator, omega, ORDER))
    print("group generated by omega equals the solutions of x^n == 1: %d residues" % len(ring_set))
    print("half-order impostor: order %d, %d residues, proper subgroup: %s"
          % (ORDER // 2, len(impostor_set), impostor_set < ring_set))
    print("cheap invariants match (identity, sum, sum of squares, group law): %s" % (right == wrong,))
    print("sheet %dx%d, lit roots %d of %d cells" % (width, height, lit, cells))
    print("wrote %s (%dx%d, grayscale)" % (out, big_width, big_height))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
