"""Real chain entropy streamed through the beams, and whether the object is recovered through them.

    python examples/00_blob_viz_tools/beam_illuminate.py --check
    python examples/00_blob_viz_tools/beam_illuminate.py            the four light sources, graded on recovery
    python examples/00_blob_viz_tools/beam_illuminate.py --entropy   what the chain is worth as a noise source

THE CLAIM UNDER TEST

beam_rows.py already carries the illumination model in its own words: what stops the carried beam
is the bit being set, what casts the shadow is the stopping, and the pattern on the wall is the
state. So the beams are rays, and this gives them a real light source instead of a synthetic
seed.

WHERE THE ENTROPY ACTUALLY ENTERS

The obvious reading is to modulate each beam's intensity. That would be wrong and it is worth
saying why: scaling the rows of a matrix by a diagonal cannot change its rank, an intensity
pattern would leave the reading's reach untouched however random it was. The experiment would
measure nothing.

The entropy has to choose WHERE THE BEAMS POINT. Direction decides which sources a ray passes.
It decides what the shadow can resolve. That makes the light source a property of the geometry
and not a scaling, and it makes the claim falsifiable:

    ILLUMINATION WORKS      the object is recovered from its shadows
    ILLUMINATION FAILS      the shadows do not determine the object

FOUR SOURCES, AND TWO OF THEM ARE CONTROLS

    chain       real block headers from the verified corpus, hashed into directions
    csprng      an ideal source, the upper bound any real source is graded against
    degenerate  every beam pointed the same way. NO ENTROPY AT ALL. This must FAIL, and if it
                recovers the object then direction never mattered and the claim is empty.
    golden      the structured placement beam_rows.py already uses, for reference

A NULL HERE WOULD BE THE DEGENERATE ROW RECOVERING THE OBJECT. That is the outcome that would
refute the idea. It is run and not assumed.
"""

import argparse
import hashlib
import io
import json
import math
import os
import sys

import numpy

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import beam_rows

CORPUS = os.path.join(ROOT, "utils", "maint", "chain", "blocks_deep.json")
SOURCES = beam_rows.COUNT          # 256


def chain_bytes(want):
    """Entropy from the chain: the verified corpus's own block ids, concatenated.

    NOT HASHED INTO A STREAM CIPHER. Hashing would launder any structure the chain has and the
    experiment would then be measuring SHA-256's output and not the chain's. The ids are used
    as they are, the only way the chain can be graded as a source and not as a seed.

    A block id is already the output of the proof of work. These bytes are the most expensive
    random numbers in existence. That is the ground on which for preferring them to a local generator: they
    are witnessed and they cannot be regenerated by anyone who did not do the work.
    """
    if not os.path.exists(CORPUS):
        return None
    with io.open(CORPUS, encoding="utf-8") as handle:
        blocks = json.load(handle)
    blocks = sorted(blocks, key=lambda one: one["height"], reverse=True)

    out = bytearray()
    for block in blocks:
        text = block.get("id") or ""
        try:
            raw = bytes.fromhex(text)
        except ValueError:
            continue
        # THE LEADING ZERO BYTES ARE THE PROOF OF WORK AND CARRY NO ENTROPY WHATSOEVER. Measured
        # over 200 ids from this corpus: every single one begins with 9 or 10 zero bytes, and the
        # byte-value collision deficit over the raw stream is 4.541 bits against a floor of
        # 5.603e-03, which is eight hundred times the floor.
        #
        # This is not a flaw in the chain, it is the chain working. A block id is small BECAUSE
        # somebody spent 5.47e23 hashes making it small. The high bytes are the receipt and the
        # low bytes are the noise. Beams aimed off the raw stream reach rank 175 of 256 and leave
        # 23 bits of the object unrecovered.
        #
        # So the entropy is taken from the TAIL. Skipping the zero run is not enough on its own,
        # because the first nonzero byte is itself biased small by the same target. The whole
        # run of leading zeros plus one is dropped.
        at = 0
        while (at < len(raw)) and (raw[at] == 0):
            at += 1
        out.extend(raw[at + 1:])
        if len(out) >= want:
            break
    return bytes(out[:want]) if len(out) >= want else None


def directions_from(stream, count):
    """Turn a byte stream into `count` unit directions on the sphere.

    Two bytes an angle. Four bytes a direction. The mapping is area-preserving: the cosine of
    the colatitude is taken uniform and not the angle itself, or the directions would crowd the
    poles and the placement would carry a bias the source did not have.
    """
    out = numpy.zeros((count, 3))
    for at in range(count):
        chunk = stream[(at * 4) % max(1, len(stream) - 4):][:4]
        if len(chunk) < 4:
            chunk = (chunk + stream)[:4]
        first = int.from_bytes(chunk[0:2], "big") / 65535.0
        second = int.from_bytes(chunk[2:4], "big") / 65535.0
        cosine = 2.0 * first - 1.0
        sine = math.sqrt(max(0.0, 1.0 - cosine * cosine))
        angle = 2.0 * math.pi * second
        out[at] = (sine * math.cos(angle), sine * math.sin(angle), cosine)
    return out


def light_sources(count):
    """The four sources, as (name, directions, what it is)."""
    out = []

    stream = chain_bytes(count * 4 + 8)
    if stream is not None:
        out.append(("chain", directions_from(stream, count), "real block ids, unhashed"))
    else:
        out.append(("chain", None, "corpus absent"))

    generator = numpy.random.default_rng(20260912)
    ideal = generator.standard_normal((count, 3))
    ideal = ideal / numpy.linalg.norm(ideal, axis=1, keepdims=True)
    out.append(("csprng", ideal, "an ideal source, the upper bound"))

    # NO ENTROPY. Every beam on one axis, with only the tiny jitter needed to keep the origins
    # distinct. This is the control that decides whether direction matters at all.
    degenerate = numpy.tile(numpy.array([0.0, 0.0, 1.0]), (count, 1))
    degenerate[:, 0] += numpy.linspace(0.0, 1e-9, count)
    degenerate = degenerate / numpy.linalg.norm(degenerate, axis=1, keepdims=True)
    out.append(("degenerate", degenerate, "all beams parallel, no entropy"))

    out.append(("golden", numpy.array(beam_rows.source_points(count)) /
                numpy.linalg.norm(numpy.array(beam_rows.source_points(count)), axis=1, keepdims=True),
                "the structured placement already in use"))
    return out


def beams_aimed(directions, points):
    """A beam set whose aim comes from `directions` and not from a seed."""
    rows = []
    for at in range(len(directions)):
        start = tuple(beam_rows.ORIGIN_RADIUS * one for one in directions[at])
        # Aim back through the center. Every beam crosses the object instead of grazing it.
        aim = tuple(-one for one in directions[at])
        rows.append(beam_rows.beam_row(start, aim, points))
    return numpy.array(rows)


def illuminate(beams, occupancy):
    """The shadow pattern: what each beam reads of this object."""
    return beams.dot(occupancy)


def recover(beams, shadows):
    """The object back from its shadows, by least squares. The illumination test."""
    solution, _residuals, _rank, _values = numpy.linalg.lstsq(beams, shadows, rcond=None)
    return solution


def _report():
    points = beam_rows.source_points(SOURCES)
    generator = numpy.random.default_rng(7)
    occupancy = (generator.random(SOURCES) < 0.5).astype(float)

    print("")
    print("  %d beams lighting a %d bit object. The entropy chooses where they point." % (SOURCES, SOURCES))
    print("  Recovery error is the worst bit of the object reconstructed from its shadows alone.")
    print("")
    print("  %-12s %8s %12s %14s %14s %10s"
          % ("source", "rank", "condition", "recovery err", "bits wrong", "verdict"))

    for name, directions, _note in light_sources(SOURCES):
        if directions is None:
            print("  %-12s %8s" % (name, "absent"))
            continue
        beams = beams_aimed(directions, points)
        rank = int(numpy.linalg.matrix_rank(beams))
        values = numpy.linalg.svd(beams, compute_uv=False)
        condition = (values[0] / values[-1]) if values[-1] > 0 else float("inf")

        shadows = illuminate(beams, occupancy)
        back = recover(beams, shadows)
        error = float(numpy.abs(back - occupancy).max())
        wrong = int((numpy.abs(numpy.round(back) - occupancy) > 0.5).sum())

        works = (rank == SOURCES) and (wrong == 0)
        print("  %-12s %8d %12s %14.3e %14d %10s"
              % (name, rank,
                 ("%.3e" % condition) if math.isfinite(condition) else "singular",
                 error, wrong, "lit" if works else "DARK"))

    print("")
    print("  READ THE TABLE INSTEAD OF THIS SENTENCE.")
    print("")
    print("  The degenerate row decides the claim. Parallel beams all read the same")
    print("  line through the object. Their shadows cannot distinguish sources that differ off")
    print("  that line. If it recovers the object anyway then direction never mattered and the")
    print("  entropy is decoration.")
    return 0


def _entropy():
    """What the chain is worth as a source, in the unit collision_entropy.py argues for."""
    print("")
    stream = chain_bytes(1 << 16)
    if stream is None:
        print("  the corpus is absent. There is no chain entropy to measure")
        return 1

    print("  %d bytes of real block ids from the verified corpus." % len(stream))
    print("")
    print("  %-14s %10s %12s %14s %12s" % ("field", "bins", "chi-square", "H2 deficit bits", "floor"))

    for name, bins, extract in (("byte value", 256, lambda b: b),
                                ("low nibble", 16, lambda b: b & 0x0F),
                                ("high nibble", 16, lambda b: b >> 4),
                                ("bit parity", 2, lambda b: bin(b).count("1") & 1)):
        counts = numpy.zeros(bins)
        for byte in stream:
            counts[extract(byte)] += 1
        samples = counts.sum()
        expected = samples / bins
        chi = float(((counts - expected) ** 2 / expected).sum())
        deficit = math.log(1.0 + chi / samples, 2.0)
        floor = math.log(1.0 + (bins - 1.0) / samples, 2.0)
        print("  %-14s %10d %12.2f %14.3e %12.3e" % (name, bins, chi, deficit, floor))

    print("")
    print("  A DEFICIT AT OR UNDER THE FLOOR IS WHAT A FLAT FIELD LOOKS LIKE. The floor is what")
    print("  chance alone manufactures at this sample count, from collision_entropy.py's own")
    print("  expression. It is derived and not chosen.")
    print("")
    print("  A block id is the output of the proof of work. These are the most expensive random")
    print("  numbers in existence and they are witnessed: nobody who did not do the work can")
    print("  regenerate them. For that the chain is worth preferring to a local generator,")
    print("  even where a local one measures just as flat.")
    return 0


def _check():
    failed = 0
    points = beam_rows.source_points(SOURCES)
    generator = numpy.random.default_rng(11)
    occupancy = (generator.random(SOURCES) < 0.5).astype(float)
    print("")

    sources = dict((name, directions) for name, directions, _note in light_sources(SOURCES))

    # THE NEGATIVE CONTROL IS THE WHOLE EXPERIMENT. Parallel beams must NOT recover the object. If
    # they do, direction is irrelevant and every other row in the report is meaningless.
    beams = beams_aimed(sources["degenerate"], points)
    rank = int(numpy.linalg.matrix_rank(beams))
    back = recover(beams, illuminate(beams, occupancy))
    wrong = int((numpy.abs(numpy.round(back) - occupancy) > 0.5).sum())
    print("  degenerate light: rank %d of %d, %d bits wrong" % (rank, SOURCES, wrong))
    if rank >= SOURCES or wrong == 0:
        print("    FAIL parallel beams resolved the object. Direction does not matter and the")
        print("    illumination claim is empty")
        failed += 1

    # THE POSITIVE CONTROL. An ideal source must recover it, or the instrument cannot see anything
    # and the negative control above is satisfied trivially.
    beams = beams_aimed(sources["csprng"], points)
    rank = int(numpy.linalg.matrix_rank(beams))
    back = recover(beams, illuminate(beams, occupancy))
    wrong = int((numpy.abs(numpy.round(back) - occupancy) > 0.5).sum())
    print("  ideal light: rank %d of %d, %d bits wrong" % (rank, SOURCES, wrong))
    if rank != SOURCES or wrong != 0:
        print("    FAIL an ideal source did not recover the object")
        failed += 1

    # AND THE CHAIN MUST DO AS WELL AS THE IDEAL SOURCE, the actual claim.
    if sources.get("chain") is not None:
        beams = beams_aimed(sources["chain"], points)
        rank = int(numpy.linalg.matrix_rank(beams))
        back = recover(beams, illuminate(beams, occupancy))
        wrong = int((numpy.abs(numpy.round(back) - occupancy) > 0.5).sum())
        print("  chain light: rank %d of %d, %d bits wrong" % (rank, SOURCES, wrong))
        if rank != SOURCES or wrong != 0:
            print("    FAIL the chain did not recover the object")
            failed += 1
    else:
        print("  chain light: corpus absent. The claim is untested and not confirmed")

    # THE SHADOWS MUST DEPEND ON THE OBJECT. A reading that is the same for two different objects
    # is not a shadow of either.
    other = (generator.random(SOURCES) < 0.5).astype(float)
    beams = beams_aimed(sources["csprng"], points)
    moved = float(numpy.abs(illuminate(beams, occupancy) - illuminate(beams, other)).max())
    print("  two different objects cast shadows differing by %.4e" % moved)
    if moved < 1e-6:
        print("    FAIL the shadow does not depend on the object")
        failed += 1

    print("")
    print("  %d check(s) failed" % failed)
    return failed


def main():
    parser = argparse.ArgumentParser(description="chain entropy streamed through the beams")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--entropy", action="store_true")
    args = parser.parse_args()

    if args.check:
        return 1 if _check() else 0
    if args.entropy:
        return _entropy()
    return _report()


if __name__ == "__main__":
    sys.exit(main())
