# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational")
import os
import sys

ORIOR = "D:/git_project/repos/owned/public/orior/archive/src/python"
sys.path.insert(0, ORIOR)
from representation.constants.naturals import golden_ratio

REACH = (3, 6, 6)
AXIS_WEIGHTS = (16, 1, 1)
PLACES = 24


def main():
    scale = 10 ** PLACES
    phi = golden_ratio(PLACES)
    turn = phi - scale

    offsets = []
    for z in range(-REACH[0], REACH[0] + 1):
        for y in range(-REACH[1], REACH[1] + 1):
            for x in range(-REACH[2], REACH[2] + 1):
                if (z, y, x) == (0, 0, 0):
                    continue
                length = (AXIS_WEIGHTS[0] * z * z) + (AXIS_WEIGHTS[1] * y * y) + (AXIS_WEIGHTS[2] * x * x)
                offsets.append((length, z, y, x))

    shells = {}
    for length, z, y, x in offsets:
        shells.setdefault(length, []).append((z, y, x))

    ordered = []
    for length in sorted(shells):
        members = sorted(shells[length])
        ranked = sorted(range(len(members)), key=lambda at: ((at + 1) * turn) % scale)
        ordered.extend(members[at] for at in ranked)

    print("/* cell_tracking - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>")
    print(" * SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational")
    print(" */")
    print("/**")
    print(" * @file spiral_table.h")
    print(" * @brief Golden spiral lag offsets: nearest shells first, no direction repeated at any prefix.")
    print(" *")
    print(" * GENERATED by maint/emit_spiral_table.py. Do not edit by hand; edit the script and emit again.")
    print(" * Phi is orior's, from representation.constants.naturals, where it is an integer agreed by")
    print(" * the square root form and by the Fibonacci ratio. Nothing here is a float and no root is taken:")
    print(" * the offsets are lattice points and phi only chose the order to visit them in.")
    print(" *")
    print(" * Reach %s voxels in z y x, weighted %s, %d offsets over %d shells."
          % (str(REACH), str(AXIS_WEIGHTS), len(ordered), len(shells)))
    print(" */")
    print("")
    print("#ifndef SPIRAL_TABLE_H")
    print("#define SPIRAL_TABLE_H")
    print("")
    print("/** @brief Offsets the table holds. */")
    print("#define SPIRAL_STEPS %du" % len(ordered))
    print("")
    print("/** @brief Three per step, z y x, in the spiral's order. */")
    print("static const int SPIRAL_OFFSETS[SPIRAL_STEPS * 3] = {")
    for at in range(0, len(ordered), 6):
        print("    " + " ".join("%d, %d, %d," % one for one in ordered[at:at + 6]))
    print("};")
    print("")
    print("#endif /* SPIRAL_TABLE_H */")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
