import argparse
import io
import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_LIBRARY = "D:/git_project/repos/owned/public/orior/archive/src/python"
OUT = os.path.join(os.path.dirname(ROOT), "00_blob_viz_tools", "toolbox", "core", "turn_table.js")
PLACES = 60
SCALE = 1 << 14
TAIL = Fraction(1, 1 << 80)


def sine(angle):
    total = Fraction(0)
    term = angle
    k = 1
    while abs(term) > TAIL:
        total += term
        term = -term * angle * angle / ((k + 1) * (k + 2))
        k += 2
    return total


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--orior", default=DEFAULT_LIBRARY)
    options = parser.parse_args()
    sys.path.insert(0, options.orior)
    from representation.constants.naturals import pi

    exact_pi = Fraction(pi(PLACES), 10 ** PLACES)
    entries = []
    for degree in range(91):
        exact = sine(exact_pi * degree / 180) * SCALE
        entries.append((exact.numerator * 2 + exact.denominator) // (2 * exact.denominator))
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("// Generated by maint/emit_turn_table.py from orior representation.constants.naturals.pi(%d); do not edit.\n" % PLACES)
        handle.write("// sin(d degrees) * 2^14, rounded half up, for d = 0 to 90.\n")
        handle.write("EV.SINE_DEGREES = [%s];\n" % ", ".join(str(entry) for entry in entries))
    print("  %s: 91 entries, pi from %s at %d places" % (OUT, options.orior, PLACES))


if __name__ == "__main__":
    main()
