#!/usr/bin/env python3
# orior - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
# Catalog: EXP-x-015
#
# The symmetry group of the Riemann zeta zeros, verified exactly on Gaussian rationals, and the critical
# line shown to be its fixed set. This records structure and computes no zero; it claims nothing about
# the Riemann hypothesis.
#
#   Usage:  python examples/0_experimental/zeta_zero_symmetry.py
#
# This reads no corpus. It sits in 0_experimental: an arithmetic result shown working instead of a stage
# reading. It is an entry in the analytic-number-theory workbook and follows the same rail: claim
# nothing. Two facts about zeta are theorems and are not computed here: the functional equation makes the zero
# set invariant under s -> 1 - s, and the real coefficients make it invariant under conjugation
# s -> conj(s). Take those as given. What this file does is verify, on exact Gaussian rationals, the
# GROUP those two symmetries generate and its fixed set, which needs no zero and no zeta value at all.
#
# The two maps are involutions, each its own inverse, and together they generate the Klein four-group
# {identity, s->1-s, s->conj(s), s->1-conj(s)}. A generic point's orbit is the quadruple
# {rho, 1-rho, conj(rho), 1-conj(rho)}. The map s -> 1 - conj(s) has fixed set exactly Re(s) = 1/2, the
# critical line, and a zero on the critical line has an orbit that collapses from four points to the
# conjugate pair {rho, conj(rho)}.
#
# This is the same shape as the transform's wave inversion one level down: an involution and the fixed
# set it turns around, m -> -m fixing 0 and n/2 in ntt_double_transform_inverts.py, s -> 1 - conj(s)
# fixing the critical line here. The Riemann hypothesis is the statement that every non-trivial zero is
# a fixed point of s -> 1 - conj(s), that the four-point orbit always collapses to two. This file states
# that and does not touch it; it verifies only the group and the fixed set, which are not in question.
#
# Positive control: the maps are involutions, the group closes, the fixed set of s -> 1-conj(s) is the
# critical line, and a critical-line orbit collapses to a pair. Drawn null: a point off the line has a
# four-point orbit and is not fixed. No bounding: exact Gaussian rationals, equality only.

import io
import sys
from fractions import Fraction


def reflect(point):
    """s -> 1 - s, the functional equation's involution, on a Gaussian rational (real, imaginary)."""
    real, imaginary = point
    return (1 - real, -imaginary)


def conjugate(point):
    """s -> conj(s), from the real coefficients."""
    real, imaginary = point
    return (real, -imaginary)


def reflect_conjugate(point):
    """s -> 1 - conj(s), the composition, whose fixed set is the critical line."""
    return reflect(conjugate(point))


def orbit(point):
    """The set of images of `point` under the group generated by the two involutions."""
    return {point, reflect(point), conjugate(point), reflect_conjugate(point)}


def on_critical_line(point):
    """Whether Re(s) = 1/2 exactly."""
    return point[0] == Fraction(1, 2)


def main():
    out = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace", newline="")
    out.write("  the symmetry group of the zeta zeros, exact on Gaussian rationals; no zero computed\n")
    out.write("  this claims nothing about the Riemann hypothesis\n\n")

    # a spread of Gaussian-rational test points, none of them a zero, just carriers of the geometry
    points = [(Fraction(3, 7), Fraction(14, 1)), (Fraction(1, 2), Fraction(21, 2)),
              (Fraction(2, 5), Fraction(25, 3)), (Fraction(1, 2), Fraction(30, 7)),
              (Fraction(9, 11), Fraction(-4, 3))]

    involutions = all(reflect(reflect(point)) == point and conjugate(conjugate(point)) == point
                      and reflect_conjugate(reflect_conjugate(point)) == point for point in points)

    # the group closes: composing any two generators lands on one of the four elements
    closes = True
    for point in points:
        elements = orbit(point)
        for element in elements:
            if not orbit(element) <= elements:
                closes = False

    out.write("  the two maps and their composition are involutions (twice is the identity): %s\n"
              % involutions)
    out.write("  the four-element group closes on every orbit: %s\n\n" % closes)

    out.write("  %-22s %-8s %s\n" % ("point s", "on line", "orbit size"))
    fixed_set_correct = True
    collapse_correct = True
    for point in points:
        size = len(orbit(point))
        fixed_by_reflect_conjugate = reflect_conjugate(point) == point
        # the fixed set of s -> 1 - conj(s) is the critical line
        if fixed_by_reflect_conjugate != on_critical_line(point):
            fixed_set_correct = False
        # a point on the line has an orbit that collapses to at most the conjugate pair
        if on_critical_line(point) and size > 2:
            collapse_correct = False
        out.write("  %-22s %-8s %d\n"
                  % ("%s%+si" % (point[0], point[1]), on_critical_line(point), size))

    out.write("\n  the fixed set of s -> 1-conj(s) is exactly Re(s)=1/2, the critical line: %s\n"
              % fixed_set_correct)
    out.write("  a point on the line has an orbit collapsing to the conjugate pair: %s\n" % collapse_correct)

    # drawn null: a point off the line is not fixed and keeps a four-point orbit
    off_line = (Fraction(9, 11), Fraction(-4, 3))
    null_holds = (not on_critical_line(off_line)) and reflect_conjugate(off_line) != off_line and \
                 len(orbit(off_line)) == 4
    out.write("  a point off the line is not fixed and keeps four orbit points: %s\n" % null_holds)
    out.flush()

    return 0 if (involutions and closes and fixed_set_correct and collapse_correct and null_holds) else 1


if __name__ == "__main__":
    raise SystemExit(main())
